import { ToolItem } from '../types';
import { MORE_TOOLS } from './moreToolsData';
import { BATCH_3_TOOLS } from './batch3ToolsData';
import { BATCH_4_TOOLS } from './batch4ToolsData';
import { BATCH_5_TOOLS } from './batch5ToolsData';
import { BATCH_6_TOOLS } from './batch6ToolsData';

export const TOOLS: ToolItem[] = [
  // CRYPTO TOOLS
  {
    id: 'crypto-profit',
    name: 'Crypto Profit & Loss Calculator',
    slug: 'crypto-profit-calculator',
    route: '/crypto-profit-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Calculate crypto gains, losses, trading fees, and net return on investment (ROI).',
    description: 'Determine your net cryptocurrency profit or loss after taking into account purchase price, sale proceeds, and maker/taker trading fees across both sides of the transaction.',
    icon: 'TrendingUp',
    keywords: ['crypto profit', 'crypto loss', 'roi', 'bitcoin profit', 'crypto trading gains', 'crypto exit price', 'pnl'],
    featured: true,
    relatedTools: ["crypto-roi-calc", "crypto-dca-calc", 'crypto-trading-fee', 'crypto-break-even'],
    formulaSummary: 'Net Profit = Gross Revenue - Gross Cost - Total Trading Fees',
    formulaDetails: [
      'Gross Cost = Buy Price × Quantity',
      'Gross Revenue = Sell Price × Quantity',
      'Total Fees = Buy Fee + Sell Fee',
      'Net Profit / Loss = Gross Revenue - Gross Cost - Total Fees',
      'ROI (%) = (Net Profit / Total Investment) × 100',
    ],
    exampleCalculation: {
      title: 'Example: Bitcoin Buy & Sell Trade',
      description: 'Buying 0.5 BTC at $60,000 and selling at $72,000 with 0.1% exchange fees on both transactions.',
      inputs: {
        'Buy Price': '$60,000',
        'Sell Price': '$72,000',
        'Quantity': '0.5 BTC',
        'Buy Fee (0.1%)': '$30.00',
        'Sell Fee (0.1%)': '$36.00',
      },
      outputs: {
        'Total Invested': '$30,030.00',
        'Net Revenue': '$35,964.00',
        'Net Profit': '+$5,934.00',
        'ROI': '+19.76%',
      },
    },
    faqs: [
      {
        question: 'How do exchange fees impact my crypto profit?',
        answer: 'Most cryptocurrency exchanges charge a maker or taker fee (typically 0.1% to 0.5%) on both entering and exiting a trade. On a $10,000 trade, roundtrip fees can total $20 to $100, which directly reduces your net profits or deepens losses.',
      },
      {
        question: 'What is the difference between Gross Profit and Net Profit?',
        answer: 'Gross profit considers only the price difference multiplied by quantity (Revenue minus Cost), whereas Net profit subtracts all transaction costs, exchange fees, and gas fees.',
      },
      {
        question: 'Does this calculator factor in taxes?',
        answer: 'This tool calculates pre-tax net trading profit. For estimating capital gains taxes on your gains, use our dedicated Crypto Tax Estimate Calculator.',
      },
    ],
  },
  {
    id: 'crypto-staking',
    name: 'Crypto Staking Calculator',
    slug: 'crypto-staking-calculator',
    route: '/crypto-staking-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Forecast proof-of-stake rewards, compounding yields, and daily/monthly payouts.',
    description: 'Calculate anticipated staking yields across proof-of-stake networks (e.g. Ethereum, Solana, Cosmos). Compare simple APY against daily, weekly, or monthly auto-compounding.',
    icon: 'Coins',
    keywords: ['crypto staking', 'staking rewards', 'proof of stake', 'staking yield', 'apy calculator', 'eth staking'],
    featured: true,
    relatedTools: ["crypto-compound-interest-calc", "compound-interest-calc", 'crypto-profit'],
    formulaSummary: 'A = P × (1 + r/n)^(n×t) [Compound Mode] or P × r × t [Simple Mode]',
    formulaDetails: [
      'Simple Mode: Reward = Principal × (APY / 100) × (Days / 365)',
      'Compound Mode: Final Balance = Principal × (1 + (Rate / n))^(n × (Days / 365))',
      'where n = 365 for daily, 52 for weekly, 12 for monthly auto-compounding',
      'Daily Earnings = Total Reward / Duration (Days)',
      'Effective APY (%) = ((Final Balance / Principal)^(365 / Days) - 1) × 100',
    ],
    exampleCalculation: {
      title: 'Example: Staking 50 SOL at 7.2% APY for 1 Year',
      description: 'Staking 50 tokens with daily protocol compounding over a 365-day period.',
      inputs: {
        'Principal Tokens': '50.00',
        'Annual Rate': '7.20%',
        'Duration': '365 Days',
        'Compounding': 'Daily',
      },
      outputs: {
        'Total Reward': '+3.73 tokens',
        'Final Balance': '53.73 tokens',
        'Monthly Payout': '~0.31 tokens/mo',
        'Effective APY': '7.46%',
      },
    },
    faqs: [
      {
        question: 'What is the difference between APR and APY in staking?',
        answer: 'APR (Annual Percentage Rate) does not account for compounding rewards. APY (Annual Percentage Yield) reflects the actual yield achieved when rewards are periodically re-staked back into the principal pool.',
      },
      {
        question: 'Are staking yields guaranteed?',
        answer: 'No. Staking reward rates fluctuate based on total network stake participation, validator performance (uptime and commission fees), and network transaction volumes.',
      },
    ],
  },
  {
    id: 'crypto-trading-fee',
    name: 'Crypto Trading Fee Calculator',
    slug: 'crypto-trading-fee-calculator',
    route: '/crypto-trading-fee-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Analyze exchange maker/taker commission costs and net execution value.',
    description: 'Calculate total commission deductions on cryptocurrency spot, limit, and market orders across single trades and roundtrip roundturns.',
    icon: 'Receipt',
    keywords: ['trading fees', 'binance fee', 'coinbase fee', 'maker taker fee', 'crypto exchange fees'],
    featured: false,
    relatedTools: ['crypto-profit', 'crypto-break-even', 'crypto-position-size'],
    formulaSummary: 'Fee Amount = Trade Value × (Fee Percentage / 100)',
    formulaDetails: [
      'Trade Value = Amount (or Units × Price)',
      'Fee Amount = Trade Value × (Fee Rate / 100)',
      'Roundtrip Fee = Entry Fee + Exit Fee (2× for equal-sized trades)',
      'Net Amount Received = Trade Value - Fee Amount',
    ],
    exampleCalculation: {
      title: 'Example: $25,000 Taker Order at 0.20% Fee',
      description: 'Executing an instantaneous market order of $25,000 on a centralized exchange.',
      inputs: {
        'Trade Amount': '$25,000.00',
        'Fee Rate': '0.20%',
        'Order Side': 'Roundtrip Trade',
      },
      outputs: {
        'Total Fee Cost': '$100.00',
        'Net Proceeds': '$24,900.00',
        'Effective Rate': '0.40%',
      },
    },
    faqs: [
      {
        question: 'What is the difference between a Maker and Taker fee?',
        answer: 'Makers add liquidity to the order book (e.g., limit orders placed away from current market price) and usually pay lower fees. Takers remove liquidity instantly (e.g., market orders) and typically incur higher fees.',
      },
      {
        question: 'Can I reduce crypto exchange fees?',
        answer: 'Yes. Most exchanges offer discounts for holding their native exchange token (e.g., BNB), reaching higher 30-day trading volume tiers, or utilizing limit orders instead of market orders.',
      },
    ],
  },
  {
    id: 'crypto-break-even',
    name: 'Crypto Break-Even Calculator',
    slug: 'crypto-break-even-calculator',
    route: '/crypto-break-even-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Calculate the exact exit price required to cover purchase costs and exchange fees.',
    description: 'Determine the exact target price you must sell your crypto asset at so you recover 100% of your initial capital plus all entry and exit exchange fees.',
    icon: 'Scale',
    keywords: ['break even calculator', 'crypto break even', 'break even price', 'zero loss exit', 'trading costs'],
    featured: false,
    relatedTools: ['crypto-profit', 'crypto-trading-fee', 'crypto-position-size'],
    formulaSummary: 'Break-Even Price = Total Cost / (Quantity × (1 - Exit Fee Rate))',
    formulaDetails: [
      'Initial Cost = (Entry Price × Quantity) + Entry Fee + Flat Fees',
      'Net Exit Factor = 1 - (Exit Fee Rate / 100)',
      'Break-Even Price = Initial Cost / (Quantity × Net Exit Factor)',
      'Required % Increase = ((Break-Even Price - Entry Price) / Entry Price) × 100',
    ],
    exampleCalculation: {
      title: 'Example: Break-Even on 2.0 ETH at $3,200 Entry',
      description: 'Buying 2.0 ETH at $3,200 with 0.25% buy fee and 0.25% anticipated exit fee.',
      inputs: {
        'Entry Price': '$3,200.00',
        'Quantity': '2.00 ETH',
        'Buy Fee': '0.25%',
        'Sell Fee': '0.25%',
      },
      outputs: {
        'Total Cost Basis': '$6,416.00',
        'Break-Even Price': '$3,216.04',
        'Price Surge Needed': '+0.501%',
      },
    },
    faqs: [
      {
        question: 'Why is the break-even price higher than my purchase price?',
        answer: 'Because exchanges charge a percentage fee when you sell your tokens as well as when you bought them. The sale price must rise enough to absorb both the buy-side fee and the future sell-side fee.',
      },
      {
        question: 'Does this factor in network gas fees for on-chain DEX swaps?',
        answer: 'Yes, you can enter gas fees as "Additional Flat Fees" in the calculator to ensure blockchain transaction costs are fully included in your break-even threshold.',
      },
    ],
  },
  {
    id: 'crypto-position-size',
    name: 'Crypto Position Size Calculator',
    slug: 'crypto-position-size-calculator',
    route: '/crypto-position-size-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Determine optimal trade size and risk capital based on stop-loss distance.',
    description: 'Calculate precise position sizing so you never risk more than 1% to 2% of your portfolio on a single cryptocurrency trade regardless of volatility.',
    icon: 'Shield',
    keywords: ['position size calculator', 'crypto risk management', 'stop loss sizing', 'trade size', 'risk reward'],
    featured: false,
    relatedTools: ['crypto-profit', 'crypto-break-even', 'crypto-trading-fee'],
    formulaSummary: 'Position Size = (Account Balance × Risk %) / |Entry Price - Stop Loss|',
    formulaDetails: [
      'Capital at Risk = Account Balance × (Risk Percentage / 100)',
      'Unit Price Risk = |Entry Price - Stop Loss Price|',
      'Position Size (Units) = Capital at Risk / Unit Price Risk',
      'Total Position Value = Position Size (Units) × Entry Price',
      '1:2 Reward Target = Entry + (2 × Unit Price Risk)',
      '1:3 Reward Target = Entry + (3 × Unit Price Risk)',
    ],
    exampleCalculation: {
      title: 'Example: $20,000 Portfolio Risking 1.5% on Bitcoin',
      description: 'Trading BTC with entry at $64,000 and stop-loss set at $61,500.',
      inputs: {
        'Portfolio Balance': '$20,000.00',
        'Risk Tolerance': '1.50%',
        'Entry Price': '$64,000.00',
        'Stop-Loss': '$61,500.00',
      },
      outputs: {
        'Max Dollar Risk': '$300.00',
        'Risk Per BTC': '$2,500.00',
        'Optimal Position': '0.1200 BTC',
        'Position Value': '$7,680.00',
        '1:2 Target': '$69,000.00',
      },
    },
    faqs: [
      {
        question: 'What is the golden rule of position sizing?',
        answer: 'Most professional traders never risk more than 1% to 2% of their total account on any single trade. Sizing is governed by the distance to your technical invalidation level (stop-loss), not emotions.',
      },
      {
        question: 'Does this calculator dictate leverage?',
        answer: 'If your required position value exceeds your account balance, leverage would be required. However, always exercise extreme caution with margin as liquidation can bypass standard stop-loss orders.',
      },
    ],
  },

  // FINANCE TOOLS
  {
    id: 'loan',
    name: 'Loan / EMI Calculator',
    slug: 'loan-calculator',
    route: '/loan-calculator',
    category: 'loans',
    categoryLabel: 'Loans & Credit',
    shortDescription: 'Compute equated monthly installments (EMI), total interest, and loan payoff schedules.',
    description: 'Calculate your exact monthly loan EMI payment, total interest charges, and total payback cost for personal loans, auto loans, or general financing.',
    icon: 'Landmark',
    keywords: ['loan calculator', 'emi calculator', 'car loan', 'personal loan', 'loan interest', 'monthly payment'],
    featured: true,
    relatedTools: ['mortgage', 'savings', "compound-interest-calc"],
    formulaSummary: 'EMI = P × r × (1 + r)^n / ((1 + r)^n - 1)',
    formulaDetails: [
      'P = Principal Loan Amount',
      'r = Monthly Interest Rate (Annual Rate / 12 / 100)',
      'n = Total Number of Monthly Payments (Tenure in Years × 12)',
      'Total Payment = EMI × n',
      'Total Interest Paid = Total Payment - Principal Loan Amount',
    ],
    exampleCalculation: {
      title: 'Example: $30,000 Auto Loan at 6.5% for 5 Years',
      description: 'Financing $30,000 over 60 monthly payments at 6.5% APR.',
      inputs: {
        'Loan Principal': '$30,000.00',
        'Interest Rate': '6.50%',
        'Tenure': '5 Years (60 mos)',
      },
      outputs: {
        'Monthly EMI': '$586.98',
        'Total Interest': '$5,218.80',
        'Total Payback': '$35,218.80',
      },
    },
    faqs: [
      {
        question: 'How does loan tenure affect total interest?',
        answer: 'A longer loan term lowers your monthly payment but substantially increases the total interest you pay over the life of the loan. A shorter term requires higher monthly installments but saves significantly on cumulative interest.',
      },
      {
        question: 'Can I pay off my loan early to save interest?',
        answer: 'Yes, making extra payments directly toward your loan principal reduces the outstanding balance faster, which shrinks future interest calculations. Check with your lender for any prepayment penalty clauses.',
      },
    ],
  },
  {
    id: 'sip',
    name: 'SIP Calculator',
    slug: 'sip-calculator',
    route: '/sip-calculator',
    category: 'investment',
    categoryLabel: 'Investment',
    shortDescription: 'Calculate maturity wealth from systematic monthly mutual fund and ETF plans.',
    description: 'Forecast the wealth accumulated through regular monthly investments in mutual funds, index funds, or equities using standard Systematic Investment Plan (SIP) formulas.',
    icon: 'CalendarDays',
    keywords: ['sip calculator', 'systematic investment plan', 'mutual fund sip', 'index fund calculator', 'monthly investment'],
    featured: true,
    relatedTools: ["compound-interest-calc", 'investment-return', "crypto-dca-calc", 'savings'],
    formulaSummary: 'M = P × [((1 + i)^n - 1) / i] × (1 + i)',
    formulaDetails: [
      'P = Regular Monthly Investment Amount',
      'i = Periodic Monthly Expected Rate of Return (Annual Rate / 12 / 100)',
      'n = Total Months of Investment (Tenure in Years × 12)',
      'Total Amount Invested = P × n',
      'Estimated Wealth Gained = Maturity Value - Total Amount Invested',
    ],
    exampleCalculation: {
      title: 'Example: $400/mo SIP for 15 Years at 11% Return',
      description: 'Investing $400 on the first of every month into a diversified broad-market fund.',
      inputs: {
        'Monthly SIP': '$400.00',
        'Expected Return': '11.00% / yr',
        'Investment Horizon': '15 Years',
      },
      outputs: {
        'Total Invested': '$72,000.00',
        'Estimated Returns': '+$116,929.83',
        'Total Maturity Value': '$188,929.83',
      },
    },
    faqs: [
      {
        question: 'What is a Systematic Investment Plan (SIP)?',
        answer: 'A SIP is an investment method where an investor commits a fixed sum at regular intervals (typically monthly) into mutual funds or exchange-traded funds (ETFs), fostering financial discipline and rupee/dollar cost averaging.',
      },
      {
        question: 'Are returns in mutual fund SIPs guaranteed?',
        answer: 'No. Mutual funds and equity markets fluctuate. Historical averages (e.g., 10-12% for broad index funds over long periods) are not guarantees of future returns.',
      },
    ],
  },
  {
    id: 'investment-return',
    name: 'Investment Return Calculator',
    slug: 'investment-return-calculator',
    route: '/investment-return-calculator',
    category: 'investment',
    categoryLabel: 'Investment',
    shortDescription: 'Analyze total portfolio capital growth, ROI, and annualized return (CAGR).',
    description: 'Measure total monetary profit and compound annual growth rate (CAGR) on any stock, bond, real estate, or blended investment portfolio.',
    icon: 'PieChart',
    keywords: ['investment calculator', 'investment return', 'cagr calculator', 'portfolio return', 'stock return'],
    featured: false,
    relatedTools: ["compound-interest-calc", 'sip', 'savings'],
    formulaSummary: 'Gain = Future Value - Total Invested; ROI = (Gain / Total Invested) × 100',
    formulaDetails: [
      'Total Capital Invested = Initial Deposit + (Monthly Contribution × Total Months)',
      'Ending Portfolio Balance = Future Value under projected annual rate',
      'Total Net Gain = Ending Balance - Total Capital Invested',
      'CAGR (%) = ((Ending Balance / Initial Capital)^(1 / Years) - 1) × 100',
    ],
    exampleCalculation: {
      title: 'Example: $15,000 Investment at 9% for 10 Years',
      description: 'Lump-sum investment with $100 monthly additions over a decade.',
      inputs: {
        'Initial Outlay': '$15,000.00',
        'Monthly Addition': '$100.00',
        'Annual Rate': '9.00%',
        'Years': '10 Years',
      },
      outputs: {
        'Total Invested': '$27,000.00',
        'Ending Value': '$55,004.88',
        'Total Net Profit': '+$28,004.88',
        'ROI': '+103.72%',
      },
    },
    faqs: [
      {
        question: 'What is Compound Annual Growth Rate (CAGR)?',
        answer: 'CAGR is the mean annual growth rate of an investment over a specified period of time longer than one year. It smooths out volatility to show what constant rate would have produced the ending balance.',
      },
      {
        question: 'Should I adjust for inflation?',
        answer: 'Yes, nominal returns reflect raw dollar growth. Real returns subtract the rate of inflation (historically 2-3% per year) to show true purchasing power gains.',
      },
    ],
  },
  {
    id: 'savings',
    name: 'Savings Calculator',
    slug: 'savings-calculator',
    route: '/savings-calculator',
    category: 'savings',
    categoryLabel: 'Savings & Goals',
    shortDescription: 'Project future savings balances in High-Yield Savings Accounts (HYSA) and CDs.',
    description: 'Calculate how fast your emergency fund or financial savings target will grow with regular deposits and competitive bank interest rates.',
    icon: 'PiggyBank',
    keywords: ['savings calculator', 'hysa calculator', 'emergency fund', 'high yield savings', 'savings growth'],
    featured: false,
    relatedTools: ["compound-interest-calc", 'sip', 'loan'],
    formulaSummary: 'Future Savings = Principal Growth + Recurring Annuity Growth',
    formulaDetails: [
      'Total Deposits = Initial Deposit + (Monthly Savings × Months)',
      'Monthly Rate = Annual Percentage Yield / 12 / 100',
      'Compound Monthly Interest accrued on rolling balance',
      'Total Interest Earned = Final Savings Balance - Total Deposits',
    ],
    exampleCalculation: {
      title: 'Example: Building an Emergency Fund at 4.75% APY',
      description: 'Starting with $3,000 and contributing $250 every month for 3 years in a HYSA.',
      inputs: {
        'Initial Deposit': '$3,000.00',
        'Monthly Deposit': '$250.00',
        'Annual Rate (HYSA)': '4.75%',
        'Duration': '3 Years',
      },
      outputs: {
        'Total Out-of-Pocket': '$12,000.00',
        'Interest Earned': '+$1,130.65',
        'Final Balance': '$13,130.65',
      },
    },
    faqs: [
      {
        question: 'What is a High-Yield Savings Account (HYSA)?',
        answer: 'A HYSA is an FDIC- or NCUA-insured savings account that pays a significantly higher interest rate (often 10x to 12x higher) than traditional big-bank brick-and-mortar checking or savings accounts.',
      },
      {
        question: 'How many months of living expenses should be in savings?',
        answer: 'Most financial advisors recommend maintaining 3 to 6 months of essential living expenses in an accessible, liquid, high-yield account for an emergency fund.',
      },
    ],
  },
  {
    id: 'mortgage',
    name: 'Mortgage Calculator',
    slug: 'mortgage-calculator',
    route: '/mortgage-calculator',
    category: 'loans',
    categoryLabel: 'Loans & Credit',
    shortDescription: 'Calculate monthly home mortgage payments, interest, taxes, and loan-to-value (LTV).',
    description: 'Calculate your full monthly housing payment (PITI: Principal, Interest, Taxes, and Insurance) and total 15-year or 30-year home financing costs.',
    icon: 'Home',
    keywords: ['mortgage calculator', 'home loan', 'piti calculator', 'down payment', 'mortgage interest', 'housing payment'],
    featured: true,
    relatedTools: ['loan', 'savings', "compound-interest-calc"],
    formulaSummary: 'Monthly Payment = P&I + Property Tax + Insurance',
    formulaDetails: [
      'Loan Principal = Home Purchase Price - Down Payment',
      'P&I = P × r × (1 + r)^n / ((1 + r)^n - 1)',
      'Monthly Property Tax = (Home Price × Property Tax %) / 12',
      'Monthly Insurance = Annual Homeowners Insurance / 12',
      'Total Monthly Payment = P&I + Monthly Property Tax + Monthly Insurance',
      'LTV Ratio (%) = (Loan Amount / Home Price) × 100',
    ],
    exampleCalculation: {
      title: 'Example: $450,000 Home with 20% Down at 6.75% for 30 Years',
      description: 'Purchasing a $450,000 home with $90,000 down, 1.2% property tax, and $1,200/yr insurance.',
      inputs: {
        'Home Price': '$450,000.00',
        'Down Payment': '$90,000.00 (20%)',
        'Interest Rate': '6.75%',
        'Term': '30 Years',
        'Property Tax Rate': '1.20%',
        'Annual Insurance': '$1,200.00',
      },
      outputs: {
        'Loan Amount': '$360,000.00',
        'Principal & Interest': '$2,334.82/mo',
        'Property Tax': '$450.00/mo',
        'Insurance': '$100.00/mo',
        'Total Monthly Payment': '$2,884.82/mo',
        'Total Interest (30 yrs)': '$480,535.20',
      },
    },
    faqs: [
      {
        question: 'What is Private Mortgage Insurance (PMI)?',
        answer: 'If you make a down payment of less than 20% on a conventional mortgage, lenders typically require PMI to protect against default. Putting down 20% eliminates PMI requirements.',
      },
      {
        question: 'What is the 28/36 rule in mortgage qualification?',
        answer: 'Lenders commonly advise that your monthly housing costs (PITI) should not exceed 28% of your gross monthly income, and your total monthly debt payments (housing + student loans, car, credit cards) should not exceed 36%.',
      },
    ],
  },
  // 15 NEW CALCULATORS
  {
    id: 'cagr-calculator',
    name: 'CAGR Calculator',
    slug: 'cagr-calculator',
    route: '/calculators/cagr-calculator',
    category: 'finance',
    categoryLabel: 'Personal Finance',
    shortDescription: 'Calculate Compound Annual Growth Rate (CAGR), absolute return, and multi-year portfolio progression.',
    description: 'Calculate the accurate geometric Compound Annual Growth Rate (CAGR) of any investment over time, smoothing out market volatility to assess true annualized compounding.',
    icon: 'TrendingUp',
    keywords: ['cagr calculator', 'compound annual growth rate calculator', 'investment cagr calculator', 'cagr formula', 'annualized return', 'cagr growth', 'portfolio growth'],
    featured: true,
    relatedTools: ["compound-interest-calc", 'investment-return', 'sip'],
    formulaSummary: 'CAGR = (Final Value / Initial Value)^(1 / Years) - 1',
    formulaDetails: [
      'Growth Multiple = Final Value / Initial Value',
      'CAGR = (Final Value / Initial Value)^(1 / Years) - 1',
      'Absolute Gain = Final Value - Initial Value',
      'Total Return (%) = ((Final Value - Initial Value) / Initial Value) × 100',
    ],
    exampleCalculation: {
      title: 'Example: 5-Year Portfolio Growth',
      description: 'An initial investment of $10,000 growing to $28,500 over a 5-year period.',
      inputs: {
        'Initial Value': '$10,000.00',
        'Final Value': '$28,500.00',
        'Time Period': '5 Years',
      },
      outputs: {
        'CAGR': '23.30%',
        'Absolute Net Gain': '+$18,500.00',
        'Total Return': '+185.00%',
        'Growth Multiple': '2.85x',
      },
    },
    faqs: [
      {
        question: 'What does CAGR measure?',
        answer: 'CAGR (Compound Annual Growth Rate) represents the constant annual rate of return an investment would have achieved if it grew at a steady, compound rate each year from beginning to end.',
      },
      {
        question: 'Why is CAGR preferred over average annual return?',
        answer: 'Arithmetic average return distorts results when volatility is high. For example, a 50% gain followed by a 50% loss yields an average return of 0%, but your actual capital lost 25%. CAGR accurately reflects geometric reality.',
      },
      {
        question: 'Can CAGR handle negative returns?',
        answer: 'Yes, if your final value is less than your initial investment, the calculator will determine the negative compound rate of devaluation per annum.',
      },
    ],
  },
  {
    id: 'dividend-calculator',
    name: 'Dividend Calculator',
    slug: 'dividend-calculator',
    route: '/calculators/dividend-calculator',
    category: 'finance',
    categoryLabel: 'Personal Finance',
    shortDescription: 'Calculate dividend income, dividend yield, and long-term DRIP reinvestment compounding.',
    description: 'Project quarterly and annual passive dividend cash flow, dividend yield on cost, and future portfolio size with automated Dividend Reinvestment Plans (DRIP).',
    icon: 'Percent',
    keywords: ['dividend calculator', 'dividend yield calculator', 'stock dividend calculator', 'dividend income', 'drip calculator', 'dividend reinvestment', 'passive income'],
    featured: true,
    relatedTools: ['investment-return', "compound-interest-calc", 'savings'],
    formulaSummary: 'Annual Dividend Income = Shares Owned × Dividend Per Share',
    formulaDetails: [
      'Dividend Yield (%) = (Annual Dividend Per Share / Stock Price) × 100',
      'Annual Dividend Income = Shares Owned × Annual Dividend Per Share',
      'Payout Per Period = Annual Income / Compounding Periods per Year',
      'DRIP Future Value = Compounded shares accumulation via dividend reinvestment',
    ],
    exampleCalculation: {
      title: 'Example: Dividend Aristocrat Portfolio',
      description: 'Holding 100 shares of a $150 stock paying $4.50 annual dividend per share with 5% annual dividend growth and DRIP enabled.',
      inputs: {
        'Stock Price': '$150.00',
        'Shares Owned': '100',
        'Annual Dividend / Share': '$4.50',
        'Dividend Growth Rate': '5% / yr',
        'Time Horizon': '10 Years',
      },
      outputs: {
        'Current Dividend Yield': '3.00%',
        'Annual Dividend Income': '$450.00',
        'Future Portfolio (Yr 10)': '$23,120.50',
        'Cumulative Dividends': '$6,120.50',
      },
    },
    faqs: [
      {
        question: 'What is dividend yield and how is it calculated?',
        answer: 'Dividend yield is the percentage of a company stock price paid out in dividends each year. It equals Annual Dividend per Share divided by the current Share Price.',
      },
      {
        question: 'What is DRIP (Dividend Reinvestment Plan)?',
        answer: 'DRIP automatically uses your cash dividend distributions to purchase additional shares of the stock or ETF, compounding share ownership without manual broker intervention.',
      },
      {
        question: 'What is Yield on Cost?',
        answer: 'Yield on cost measures the annual dividend income relative to the price originally paid for the shares, demonstrating how dividend growth increases return on original capital.',
      },
    ],
  },
  {
    id: 'inflation-calculator',
    name: 'Inflation Calculator',
    slug: 'inflation-calculator',
    route: '/calculators/inflation-calculator',
    category: 'finance',
    categoryLabel: 'Personal Finance',
    shortDescription: 'Calculate the erosion of purchasing power and future costs of living across multi-year inflation cycles.',
    description: 'See how inflation degrades the real purchasing power of cash over time and calculate the future equivalent monetary cost of goods and services.',
    icon: 'ShieldAlert',
    keywords: ['inflation calculator', 'purchasing power calculator', 'inflation rate calculator', 'future cost calculator', 'cumulative inflation', 'cost of living', 'currency devaluation'],
    featured: false,
    relatedTools: ['retirement-calculator', 'savings', "compound-interest-calc"],
    formulaSummary: 'Future Cost = Current Amount × (1 + Inflation Rate)^Years',
    formulaDetails: [
      'Future Equivalent Cost = Current Amount × (1 + Inflation Rate)^Years',
      'Real Purchasing Power = Current Amount / (1 + Inflation Rate)^Years',
      'Loss in Purchasing Power (%) = ((Current - Real Power) / Current) × 100',
      'Cumulative Inflation Multiplier = (1 + Inflation Rate)^Years',
    ],
    exampleCalculation: {
      title: 'Example: $10,000 Cash Over 15 Years',
      description: 'Observing the purchasing power erosion of $10,000 over 15 years at an average 3.5% annual inflation rate.',
      inputs: {
        'Current Amount': '$10,000.00',
        'Average Inflation Rate': '3.50%',
        'Years': '15',
      },
      outputs: {
        'Future Equivalent Cost': '$16,753.49',
        'Purchasing Power Left': '$5,968.91',
        'Purchasing Power Loss': '-40.31%',
        'Inflation Multiplier': '1.675x',
      },
    },
    faqs: [
      {
        question: 'How does inflation reduce purchasing power?',
        answer: 'As prices for consumer goods and services rise over time, each unit of currency buys fewer goods. A fixed sum of uninvested money loses real purchasing power exponentially.',
      },
      {
        question: 'What is the Rule of 72 in inflation?',
        answer: 'Divide 72 by the annual inflation rate to approximate how many years it will take for prices to double or for cash purchasing power to be halved. At 3.6% inflation, prices double every 20 years.',
      },
      {
        question: 'How can investors protect wealth against inflation?',
        answer: 'Assets with intrinsic scarcity or earnings power—such as productive equities, real estate, inflation-protected bonds (TIPS), and Bitcoin—historically provide hedges against monetary inflation.',
      },
    ],
  },
  {
    id: 'retirement-calculator',
    name: 'Retirement Calculator',
    slug: 'retirement-calculator',
    route: '/calculators/retirement-calculator',
    category: 'finance',
    categoryLabel: 'Personal Finance',
    shortDescription: 'Plan your retirement nest egg with contributions, compound returns, inflation adjustments, and safe withdrawal rates.',
    description: 'Calculate your projected retirement portfolio size, compare nominal vs inflation-adjusted savings, and evaluate monthly passive cash flow based on the 4% safe withdrawal rule.',
    icon: 'Calendar',
    keywords: ['retirement calculator', 'retirement savings calculator', 'retirement planning calculator', '401k calculator', 'pension calculator', 'safe withdrawal rate', 'nest egg calculator'],
    featured: true,
    relatedTools: ['inflation-calculator', "compound-interest-calc", 'investment-return', 'savings'],
    formulaSummary: 'Retirement Nest Egg = Current Savings × (1+r)^n + Monthly Contributions × [((1+r)^n - 1) / r]',
    formulaDetails: [
      'Nominal Savings = Compounded initial capital + regular additions',
      'Real Purchasing Power = Nominal Savings / (1 + Inflation Rate)^Years',
      'Safe Monthly Income (4% Rule) = (Final Nest Egg × 0.04) / 12',
      'Total Net Interest = Final Accumulated Balance - Total Principal Contributed',
    ],
    exampleCalculation: {
      title: 'Example: 30-Year Retirement Horizon',
      description: 'A 32-year-old retiring at 65 with $35,000 existing savings, adding $750/month at 8% annual return and 2.5% inflation.',
      inputs: {
        'Current Age': '32',
        'Retirement Age': '65 (33 years)',
        'Current Savings': '$35,000.00',
        'Monthly Contribution': '$750.00',
        'Expected Return': '8.00%',
        'Expected Inflation': '2.50%',
      },
      outputs: {
        'Nominal Nest Egg': '$1,815,420.00',
        'Real Purchasing Power': '$804,230.00',
        'Safe Monthly Income (4%)': '$6,051.40 / mo',
        'Total Contributed': '$332,000.00',
      },
    },
    faqs: [
      {
        question: 'What is the 4% Safe Withdrawal Rule?',
        answer: 'Formulated by the Trinity Study, the 4% rule suggests retirees can withdraw 4% of their initial portfolio value in the first year of retirement (adjusted for inflation thereafter) with very low probability of depleting assets over 30 years.',
      },
      {
        question: 'Why is inflation critical in retirement planning?',
        answer: 'Because costs rise continuously, a $1,000,000 portfolio 30 years from now will buy significantly less than $1,000,000 today. Our calculator displays both nominal figures and real inflation-adjusted purchasing power.',
      },
      {
        question: 'How can I catch up if I am behind on retirement savings?',
        answer: 'You can increase your monthly savings rate, extend your working years by 2-3 years to allow longer compound growth, or take advantage of IRS catch-up contribution limits on 401(k) and IRA accounts.',
      },
    ],
  },
  {
    id: 'debt-payoff-calculator',
    name: 'Debt Payoff Calculator',
    slug: 'debt-payoff-calculator',
    route: '/calculators/debt-payoff-calculator',
    category: 'loans',
    categoryLabel: 'Loans & Credit',
    shortDescription: 'Calculate debt repayment timelines, interest expense, and accelerate freedom from credit cards and personal loans.',
    description: 'Determine exactly how many months and years it will take to eliminate debt balances, calculate cumulative interest costs, and identify minimum required payment thresholds.',
    icon: 'Scale',
    keywords: ['debt payoff calculator', 'debt repayment calculator', 'debt free calculator', 'credit card payoff', 'debt avalanche', 'debt snowball', 'eliminate debt'],
    featured: true,
    relatedTools: ['loan', 'amortization-calculator', 'loan-interest-calculator'],
    formulaSummary: 'Payoff Months = -log(1 - (Balance × r) / Payment) / log(1 + r)',
    formulaDetails: [
      'Monthly Interest Charge = Balance × (APR / 1200)',
      'Monthly Principal Amortized = Monthly Payment - Monthly Interest Charge',
      'Payoff Time = Total sequential billing cycles until balance reaches zero',
      'Total Interest Paid = Sum of all monthly interest charges across the payoff horizon',
    ],
    exampleCalculation: {
      title: 'Example: Credit Card Debt Payoff',
      description: 'Paying off a $15,000 balance at 18.5% APR by committing $500 each month.',
      inputs: {
        'Debt Balance': '$15,000.00',
        'Interest Rate (APR)': '18.50%',
        'Monthly Payment': '$500.00',
      },
      outputs: {
        'Time to Debt Freedom': '41 Months (3.4 Yrs)',
        'Total Interest Paid': '$5,354.20',
        'Total Outlay': '$20,354.20',
        'Minimum Required Payment': '$232.00 / mo',
      },
    },
    faqs: [
      {
        question: 'What happens if my monthly payment is lower than monthly interest?',
        answer: 'If your monthly payment does not cover accrued monthly interest, negative amortization occurs: your debt balance increases every month and you will never become debt-free. Our calculator warns you if payments are insufficient.',
      },
      {
        question: 'What is the difference between Debt Snowball and Debt Avalanche?',
        answer: 'The Debt Avalanche method prioritizes debts with the highest interest rates first to minimize total interest paid. The Debt Snowball method pays off the smallest balances first to build psychological momentum.',
      },
      {
        question: 'How does making extra payments accelerate debt freedom?',
        answer: 'Extra payments go 100% directly toward reducing principal balance. Reducing principal immediately reduces subsequent monthly interest charges, accelerating payoff logarithmically.',
      },
    ],
  },
  {
    id: 'amortization-calculator',
    name: 'Amortization Calculator',
    slug: 'amortization-calculator',
    route: '/calculators/amortization-calculator',
    category: 'loans',
    categoryLabel: 'Loans & Credit',
    shortDescription: 'Generate complete monthly and annual loan amortization schedules with principal, interest, and extra payment savings.',
    description: 'Calculate precise reducing-balance amortization schedules for home mortgages, vehicle financing, and term loans. Analyze interest savings and payoff acceleration from extra monthly payments.',
    icon: 'Landmark',
    keywords: ['amortization calculator', 'loan amortization calculator', 'amortization schedule', 'mortgage amortization', 'principal and interest schedule', 'loan breakdown'],
    featured: true,
    relatedTools: ['loan', 'debt-payoff-calculator', 'mortgage', 'loan-interest-calculator'],
    formulaSummary: 'Payment = P × [r(1+r)^n] / [(1+r)^n - 1]',
    formulaDetails: [
      'Monthly Payment = Principal × [r(1+r)^n] / [(1+r)^n - 1]',
      'Interest Portion = Remaining Balance × (Annual Rate / 12)',
      'Principal Portion = Total Payment - Interest Portion',
      'Remaining Balance = Previous Balance - Principal Portion',
    ],
    exampleCalculation: {
      title: 'Example: $250,000 30-Year Mortgage Amortization',
      description: 'A 30-year fixed loan of $250,000 at 6.5% interest with an extra $150 added each month.',
      inputs: {
        'Loan Amount': '$250,000.00',
        'Interest Rate': '6.50%',
        'Loan Term': '30 Years (360 Mos)',
        'Extra Monthly Payment': '$150.00',
      },
      outputs: {
        'Base Monthly Payment': '$1,580.17',
        'Payoff Time Saved': '5 Yrs 10 Mos',
        'Interest Saved': '$68,432.10',
        'New Payoff Horizon': '24 Yrs 2 Mos',
      },
    },
    faqs: [
      {
        question: 'What is an amortization schedule?',
        answer: 'An amortization schedule is a complete table of periodic loan payments showing how much of each payment is allocated to interest versus principal, alongside the declining loan balance over time.',
      },
      {
        question: 'Why is early mortgage payment mostly interest?',
        answer: 'Because interest is calculated on the outstanding balance, and the balance is highest at the start of the loan. As you pay down principal over time, interest charges shrink and more of each payment pays off principal.',
      },
      {
        question: 'How do extra payments affect the amortization schedule?',
        answer: 'Extra payments apply directly to principal. This immediately lowers the balance upon which future interest is calculated, shortening the total term of the loan and saving thousands in interest.',
      },
    ],
  },
  {
    id: 'loan-interest-calculator',
    name: 'Loan Interest Calculator',
    slug: 'loan-interest-calculator',
    route: '/calculators/loan-interest-calculator',
    category: 'loans',
    categoryLabel: 'Loans & Credit',
    shortDescription: 'Calculate total interest paid, monthly payment installments, and compare amortized vs simple interest loans.',
    description: 'Accurately determine total interest charges and total loan repayments across amortized and flat-rate loans. Properly handles 0% promotional interest financing.',
    icon: 'Percent',
    keywords: ['loan interest calculator', 'total loan interest calculator', 'interest payment calculator', '0% interest loan', 'apr interest calculator', 'auto loan interest'],
    featured: false,
    relatedTools: ['loan', 'amortization-calculator', 'debt-payoff-calculator'],
    formulaSummary: 'Total Interest = Total Payments - Principal Loan Amount',
    formulaDetails: [
      'Amortized Payment = Principal × [r(1+r)^n] / [(1+r)^n - 1]',
      'Simple Interest = Principal × Annual Rate × Years',
      'Total Payment = Principal + Total Interest',
      'For 0% Interest: Monthly Payment = Principal / Number of Months; Total Interest = $0',
    ],
    exampleCalculation: {
      title: 'Example: $20,000 Auto Loan at 7.5%',
      description: 'A 4-year amortized auto financing plan of $20,000 at 7.5% annual interest.',
      inputs: {
        'Principal Loan Amount': '$20,000.00',
        'Interest Rate': '7.50%',
        'Loan Term': '4 Years (48 Mos)',
        'Calculation Method': 'Amortized',
      },
      outputs: {
        'Monthly Payment': '$483.58',
        'Total Interest Paid': '$3,211.84',
        'Total Payment': '$23,211.84',
        'Interest-to-Principal': '16.06%',
      },
    },
    faqs: [
      {
        question: 'How does the calculator handle 0% interest loans?',
        answer: 'When interest is 0%, total interest is exactly $0, total repayment equals original principal, and monthly installments equal principal divided by total months, with zero mathematical division errors.',
      },
      {
        question: 'What is the difference between simple interest and amortized interest?',
        answer: 'Simple interest calculates interest based solely on original principal throughout the entire term. Amortized interest calculates interest only on the remaining unpaid balance, which decreases each month.',
      },
      {
        question: 'What is APR vs interest rate?',
        answer: 'The interest rate represents the direct cost of borrowing the principal. APR (Annual Percentage Rate) includes both the interest rate and mandatory lender fees, points, and origination charges.',
      },
    ],
  },
  {
    id: 'leverage-calculator',
    name: 'Leverage Calculator',
    slug: 'leverage-calculator',
    route: '/calculators/leverage-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Calculate trading position exposure, leverage multiples (1x-125x), required collateral, and maximum drawdown buffers.',
    description: 'Evaluate cryptocurrency and forex margin leverage, calculate total notional exposure from margin collateral, and determine maximum adverse price drawdowns before 100% equity loss.',
    icon: 'Zap',
    keywords: ['leverage calculator', 'crypto leverage calculator', 'trading leverage calculator', 'margin exposure', 'crypto leverage ratio', 'position leverage', 'binance leverage'],
    featured: true,
    relatedTools: ['margin-calculator', 'liquidation-price-calculator', 'futures-pnl-calculator'],
    formulaSummary: 'Total Exposure = Available Margin × Leverage Multiple',
    formulaDetails: [
      'Total Position Exposure = Account Margin × Leverage Ratio',
      'Borrowed Funds = Total Exposure - Initial Margin',
      'Asset Units Controlled = Total Position Exposure / Asset Price',
      'Max Adverse Drawdown (%) = 100% / Leverage Multiple',
    ],
    exampleCalculation: {
      title: 'Example: 10x Bitcoin Leverage Position',
      description: 'Opening a position with $2,500 collateral at 10x leverage on Bitcoin priced at $65,000.',
      inputs: {
        'Available Margin': '$2,500.00',
        'Leverage Multiple': '10x',
        'Asset Price': '$65,000.00',
      },
      outputs: {
        'Total Position Exposure': '$25,000.00',
        'Borrowed Capital': '$22,500.00',
        'BTC Controlled': '0.3846 BTC',
        'Max Drawdown Allowed': '-10.00%',
      },
    },
    faqs: [
      {
        question: 'What is leverage in crypto trading?',
        answer: 'Leverage allows traders to open positions significantly larger than their available capital by borrowing funds from the exchange. While it amplifies profits, it amplifies downside risk proportionally.',
      },
      {
        question: 'How does leverage affect maximum allowable drawdown?',
        answer: 'At 10x leverage, a 10% move against you consumes 100% of your initial margin. At 50x leverage, only a 2% price move against you results in complete margin depletion.',
      },
      {
        question: 'Is higher leverage always riskier?',
        answer: 'Yes. Higher leverage tightens your margin of error, moves liquidation prices closer to your entry price, and exposes your position to market volatility and stop-hunts.',
      },
    ],
  },
  {
    id: 'margin-calculator',
    name: 'Margin Calculator',
    slug: 'margin-calculator',
    route: '/calculators/margin-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Calculate required initial margin, maintenance margin, and free margin for leveraged cryptocurrency contracts.',
    description: 'Compute exact margin capital requirements for crypto derivatives, perpetual swaps, and margin trades based on entry price, contract quantity, and exchange leverage brackets.',
    icon: 'Scale',
    keywords: ['margin calculator', 'crypto margin calculator', 'trading margin calculator', 'initial margin', 'maintenance margin', 'futures margin', 'margin requirement'],
    featured: false,
    relatedTools: ['leverage-calculator', 'liquidation-price-calculator', 'crypto-position-size'],
    formulaSummary: 'Required Margin = Position Value / Leverage Ratio',
    formulaDetails: [
      'Position Value = Asset Entry Price × Quantity',
      'Initial Margin = Position Value / Leverage Multiple',
      'Maintenance Margin = Position Value × Maintenance Margin Rate (%)',
      'Free Margin = Account Balance - Required Initial Margin',
    ],
    exampleCalculation: {
      title: 'Example: Ethereum Futures Margin',
      description: 'Opening a 5 ETH position at $3,200 with 20x leverage and 0.5% maintenance margin.',
      inputs: {
        'Entry Price': '$3,200.00',
        'Position Quantity': '5 ETH',
        'Leverage': '20x',
        'Account Balance': '$5,000.00',
      },
      outputs: {
        'Total Position Value': '$16,000.00',
        'Required Initial Margin': '$800.00',
        'Maintenance Margin': '$80.00',
        'Free Margin Remaining': '$4,200.00',
      },
    },
    faqs: [
      {
        question: 'What is the difference between Initial Margin and Maintenance Margin?',
        answer: 'Initial Margin is the collateral required to open a leveraged position. Maintenance Margin is the minimum collateral required to keep the position open without facing liquidation.',
      },
      {
        question: 'What happens when account equity drops below maintenance margin?',
        answer: 'When account equity falls below the maintenance margin threshold, the exchange liquidation engine triggers and automatically closes the position to protect lender capital.',
      },
      {
        question: 'What is Isolated Margin vs Cross Margin?',
        answer: 'Isolated Margin restricts risk to the specific collateral assigned to a single trade. Cross Margin shares all available balance across all open trades to prevent liquidation.',
      },
    ],
  },
  {
    id: 'liquidation-price-calculator',
    name: 'Liquidation Price Calculator',
    slug: 'liquidation-price-calculator',
    route: '/calculators/liquidation-price-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Calculate estimated crypto liquidation prices for long and short positions across Binance, Bybit, and OKX.',
    description: 'Estimate your exact liquidation price, price safety buffer, and bankruptcy price for leveraged long and short crypto positions. Factors in maintenance margin and additional wallet collateral.',
    icon: 'ShieldAlert',
    keywords: ['liquidation price calculator', 'crypto liquidation calculator', 'futures liquidation calculator', 'binance liquidation', 'bybit liquidation', 'liquidation risk', 'crypto bankruptcy price'],
    featured: true,
    relatedTools: ['leverage-calculator', 'margin-calculator', 'futures-pnl-calculator'],
    formulaSummary: 'Long Liq = Entry × (1 - 1/Lev + MMR); Short Liq = Entry × (1 + 1/Lev - MMR)',
    formulaDetails: [
      'Long Bankruptcy Price = Entry Price × (1 - 1 / Leverage)',
      'Long Liquidation Price = Entry Price × (1 - 1 / Leverage + MMR) - (Extra Margin / Qty)',
      'Short Bankruptcy Price = Entry Price × (1 + 1 / Leverage)',
      'Short Liquidation Price = Entry Price × (1 + 1 / Leverage - MMR) + (Extra Margin / Qty)',
      'Distance to Liquidation (%) = (|Entry - Liq Price| / Entry) × 100',
    ],
    exampleCalculation: {
      title: 'Example: Long BTC Position at 10x Leverage',
      description: 'Entering a Long position at $62,000 on 10x leverage with a 0.5% maintenance margin rate.',
      inputs: {
        'Position Direction': 'LONG (Buy)',
        'Entry Price': '$62,000.00',
        'Leverage': '10x',
        'Maintenance Margin Rate': '0.50%',
      },
      outputs: {
        'Estimated Liquidation Price': '$56,110.00',
        'Safety Distance': '-9.50% (-$5,890.00)',
        'Initial Margin Required': '$6,200.00',
        'Bankruptcy Price': '$55,800.00',
      },
    },
    faqs: [
      {
        question: 'Why might my exchange liquidation price differ slightly from this calculator?',
        answer: 'Calculations are deterministic standard perpetual estimates. Exchanges such as Binance, Bybit, and OKX utilize dynamic tiered maintenance margin brackets based on position size, funding rate deductions, and exchange insurance fund fees.',
      },
      {
        question: 'How can I push my liquidation price further away?',
        answer: 'You can lower your leverage multiple, add extra margin collateral to the position, or place a guaranteed Stop Loss well above your liquidation price.',
      },
      {
        question: 'What is the Bankruptcy Price?',
        answer: 'The bankruptcy price is the price level at which your initial margin is completely wiped out (100% loss). Liquidation occurs slightly before the bankruptcy price to pay exchange liquidation fees.',
      },
    ],
  },
  {
    id: 'futures-pnl-calculator',
    name: 'Futures P&L Calculator',
    slug: 'futures-pnl-calculator',
    route: '/calculators/futures-pnl-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Calculate long and short crypto futures net profits, trading fees, ROI, and Return on Equity (ROE).',
    description: 'Comprehensive futures profit and loss calculator supporting both Long and Short positions, exchange leverage, maker/taker commissions, and net return on margin equity.',
    icon: 'TrendingUp',
    keywords: ['futures pnl calculator', 'crypto futures calculator', 'futures profit calculator', 'perpetual futures pnl', 'long short roe', 'futures fees', 'crypto derivatives pnl'],
    featured: true,
    relatedTools: ['crypto-profit', 'liquidation-price-calculator', 'risk-reward-calculator'],
    formulaSummary: 'Net P&L = Gross P&L - Roundtrip Exchange Trading Fees',
    formulaDetails: [
      'Gross P&L (Long) = (Exit Price - Entry Price) × Quantity',
      'Gross P&L (Short) = (Entry Price - Exit Price) × Quantity',
      'Total Fees = (Entry Notional × Entry Fee Rate) + (Exit Notional × Exit Fee Rate)',
      'Net P&L = Gross P&L - Total Fees',
      'ROE (%) = (Net P&L / Initial Margin) × 100',
    ],
    exampleCalculation: {
      title: 'Example: Long BTC Perpetual Trade with 10x Leverage',
      description: 'Buying 0.5 BTC at $60,000 and closing at $64,500 with 10x leverage and 0.05% taker fees.',
      inputs: {
        'Direction': 'LONG',
        'Leverage': '10x',
        'Entry Price': '$60,000.00',
        'Exit Price': '$64,500.00',
        'Quantity': '0.5 BTC',
        'Fee Rate': '0.05% / side',
      },
      outputs: {
        'Initial Margin Required': '$3,000.00',
        'Gross Profit': '+$2,250.00',
        'Roundtrip Fees': '$31.13',
        'Net Profit': '+$2,218.88',
        'ROE (%)': '+73.96%',
      },
    },
    faqs: [
      {
        question: 'Why are futures trading fees calculated on notional size rather than margin?',
        answer: 'Exchanges charge maker and taker fees based on the full notional position value (Quantity × Price), not just your initial margin deposit. At 20x leverage, fees can consume a notable portion of your actual collateral.',
      },
      {
        question: 'What is ROE (Return on Equity)?',
        answer: 'ROE measures the percentage gain or loss relative to the initial margin deposited, demonstrating the leveraged percentage return on your own capital.',
      },
      {
        question: 'How do Short positions make money when prices drop?',
        answer: 'In a Short contract, you borrow and sell an asset at the entry price and agree to repurchase it at the exit price. When the price falls, repurchasing costs less than the proceeds generated from selling.',
      },
    ],
  },
  {
    id: 'risk-reward-calculator',
    name: 'Risk/Reward Calculator',
    slug: 'risk-reward-calculator',
    route: '/calculators/risk-reward-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Calculate risk-to-reward ratios (R:R), break-even win rates, and monetary risk for long and short trade setups.',
    description: 'Determine your exact trading risk-to-reward ratio, calculate required break-even win rates, and evaluate trade quality before executing market orders.',
    icon: 'Target',
    keywords: ['risk reward calculator', 'risk reward ratio calculator', 'trading risk calculator', 'rr ratio', 'win rate calculator', 'crypto risk management', 'stop loss take profit ratio'],
    featured: true,
    relatedTools: ['take-profit-calculator', 'crypto-position-size', 'break-even-price-calculator'],
    formulaSummary: 'Risk = |Entry - Stop Loss|; Reward = |Take Profit - Entry|; Ratio = Reward / Risk',
    formulaDetails: [
      'Risk per Unit = |Entry Price - Stop Loss Price|',
      'Reward per Unit = |Take Profit Price - Entry Price|',
      'Risk/Reward Ratio = Reward per Unit / Risk per Unit',
      'Break-Even Win Rate (%) = (1 / (1 + Ratio)) × 100',
      'Total Capital at Risk = Risk per Unit × Quantity',
    ],
    exampleCalculation: {
      title: 'Example: 1 : 3.0 Risk-to-Reward Trade Setup',
      description: 'Entering a long trade at $100 with stop loss at $95 and take profit target at $115 on 50 units.',
      inputs: {
        'Entry Price': '$100.00',
        'Stop Loss Price': '$95.00',
        'Take Profit Target': '$115.00',
        'Position Quantity': '50 Units',
      },
      outputs: {
        'Risk / Reward Ratio': '1 : 3.00',
        'Break-Even Win Rate': '25.00%',
        'Capital at Risk': '-$250.00',
        'Target Profit': '+$750.00',
      },
    },
    faqs: [
      {
        question: 'What is an acceptable Risk/Reward Ratio for active trading?',
        answer: 'Most professional traders seek setups with a minimum ratio of 1:2 or 1:3. With a 1:3 ratio, you only need to win 25% of your trades to break even over time.',
      },
      {
        question: 'How is the required break-even win rate calculated?',
        answer: 'The formula is 1 / (1 + R:R). For a 1:2 ratio, 1 / (1 + 2) = 33.33%. For a 1:1 ratio, 1 / (1 + 1) = 50.00%.',
      },
      {
        question: 'Why should I define my stop loss before entering a trade?',
        answer: 'Pre-defining stop loss and take profit targets prevents emotional decision-making, enforces positive expectancy, and guarantees that losses stay within your risk tolerance.',
      },
    ],
  },
  {
    id: 'take-profit-calculator',
    name: 'Take Profit Calculator',
    slug: 'take-profit-calculator',
    route: '/calculators/take-profit-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Calculate target take-profit exit prices from entry price, stop loss, and desired risk/reward ratios.',
    description: 'Accurately project take-profit target prices for Long and Short trades based on risk per share/coin, target risk/reward multiples, and multi-tier partial exit ladders.',
    icon: 'Target',
    keywords: ['take profit calculator', 'trading take profit calculator', 'crypto take profit calculator', 'tp calculator', 'take profit stop loss', 'risk reward target', 'exit target calculator'],
    featured: false,
    relatedTools: ['risk-reward-calculator', 'break-even-price-calculator', 'crypto-position-size'],
    formulaSummary: 'Long TP = Entry + (Risk × Ratio); Short TP = Entry - (Risk × Ratio)',
    formulaDetails: [
      'Risk per Unit = |Entry Price - Stop Loss Price|',
      'Long Target Price = Entry Price + (Risk per Unit × Desired Ratio)',
      'Short Target Price = Entry Price - (Risk per Unit × Desired Ratio)',
      'Projected Profit = Reward per Unit × Position Quantity',
    ],
    exampleCalculation: {
      title: 'Example: Long Ethereum Target with 1:2.5 Ratio',
      description: 'Buying 2 ETH at $2,500 with a stop loss at $2,400 seeking a 1:2.5 risk/reward target.',
      inputs: {
        'Entry Price': '$2,500.00',
        'Stop Loss Price': '$2,400.00',
        'Desired Ratio': '2.5x',
        'Quantity': '2 ETH',
      },
      outputs: {
        'Take Profit Target Price': '$2,750.00',
        'Unit Risk vs Reward': '$100.00 Risk / $250.00 Reward',
        'Total Profit at Target': '+$500.00',
        'Target % Move': '+10.00%',
      },
    },
    faqs: [
      {
        question: 'How do partial take-profit levels work?',
        answer: 'A multi-tier take profit ladder (TP1, TP2, TP3) allows you to close portions of your trade (e.g. 33% at 1:1, 33% at 1:2, and 34% at 1:3) to lock in profits while letting runners capture larger trends.',
      },
      {
        question: 'Should I move my stop loss to break-even once TP1 is hit?',
        answer: 'Many risk management frameworks recommend trailing your stop loss to the entry price once TP1 is reached to convert the remaining position into a risk-free trade.',
      },
      {
        question: 'Does this calculator work for Short trades?',
        answer: 'Yes, select SHORT to calculate downside take-profit targets that are positioned symmetrically below your entry price.',
      },
    ],
  },
  {
    id: 'break-even-price-calculator',
    name: 'Break-Even Price Calculator',
    slug: 'break-even-price-calculator',
    route: '/calculators/break-even-price-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Calculate the exact exit price required to clear exchange maker and taker commissions with zero loss.',
    description: 'Determine the exact break-even exit price for crypto trades accounting for roundtrip exchange trading fees, ensuring you never exit a position at a hidden loss.',
    icon: 'Scale',
    keywords: ['break even calculator', 'crypto break even calculator', 'break even price calculator', 'trading break even', 'exchange fee break even', 'cost basis break even'],
    featured: false,
    relatedTools: ['crypto-break-even', 'crypto-trading-fee', 'take-profit-calculator'],
    formulaSummary: 'Long BE Price = Entry × (1 + Buy Fee) / (1 - Sell Fee)',
    formulaDetails: [
      'Gross Cost Basis = Entry Price × Quantity',
      'Total Entry Cost = Gross Cost Basis × (1 + Entry Fee Rate)',
      'Break-Even Exit Price (Long) = Entry Price × (1 + Entry Fee Rate) / (1 - Exit Fee Rate)',
      'Break-Even Exit Price (Short) = Entry Price × (1 - Entry Fee Rate) / (1 + Exit Fee Rate)',
      'Price Spread Needed (%) = (|BE Price - Entry Price| / Entry Price) × 100',
    ],
    exampleCalculation: {
      title: 'Example: Bitcoin Trade Break-Even',
      description: 'Buying 1 BTC at $65,000 with 0.1% entry fee and 0.1% exit fee.',
      inputs: {
        'Entry Price': '$65,000.00',
        'Quantity': '1 BTC',
        'Entry Fee': '0.10%',
        'Exit Fee': '0.10%',
      },
      outputs: {
        'Break-Even Exit Price': '$65,130.13',
        'Price Spread Required': '+$130.13 (+0.20%)',
        'Total Roundtrip Fees': '$130.13',
        'Net Profit at BE': '$0.00',
      },
    },
    faqs: [
      {
        question: 'Why is the break-even price higher than simply adding fee percentages together?',
        answer: 'Because the exit fee is charged on the higher exit value rather than just the entry cost. The exact formula Entry × (1 + Buy Fee) / (1 - Sell Fee) mathematically accounts for this geometric difference.',
      },
      {
        question: 'Does this calculator support 0% fee exchanges or maker rebates?',
        answer: 'Yes, enter 0% for either fee side to calculate zero-commission break-even levels.',
      },
      {
        question: 'How do network gas fees factor in?',
        answer: 'For DEX transactions on Ethereum or Solana, add network gas fees into the total cost basis to determine your comprehensive decentralized break-even threshold.',
      },
    ],
  },
  {
    id: 'apy-apr-calculator',
    name: 'APY/APR Calculator',
    slug: 'apy-apr-calculator',
    route: '/calculators/apy-apr-calculator',
    category: 'crypto',
    categoryLabel: 'Cryptocurrency',
    shortDescription: 'Convert APR to APY and APY to APR across daily, weekly, monthly, and continuous compounding schedules.',
    description: 'Convert between Annual Percentage Rate (APR) and Annual Percentage Yield (APY) for crypto staking, liquidity pools, high-yield savings, and DeFi yield farming.',
    icon: 'Percent',
    keywords: ['apy calculator', 'apr calculator', 'apy vs apr calculator', 'crypto apy calculator', 'apr to apy', 'compounding frequency', 'crypto staking yield'],
    featured: true,
    relatedTools: ['crypto-staking', "crypto-compound-interest-calc", "compound-interest-calc"],
    formulaSummary: 'APY = (1 + APR/n)^n - 1; APR = n × ((1 + APY)^(1/n) - 1)',
    formulaDetails: [
      'APR to APY = (1 + APR / n)^n - 1',
      'APY to APR = n × ((1 + APY)^(1/n) - 1)',
      'Continuous APY = e^r - 1',
      'Compounding Spread = APY - APR',
      'Ending Balance = Principal × (1 + APY)^Years',
    ],
    exampleCalculation: {
      title: 'Example: 12% Crypto Staking APR with Daily Compounding',
      description: 'Staking $10,000 at 12% APR with daily compounding (n = 365) over 1 year.',
      inputs: {
        'APR Rate': '12.00%',
        'Compounding Frequency': 'Daily (365x/year)',
        'Investment Principal': '$10,000.00',
        'Period': '1 Year',
      },
      outputs: {
        'Effective APY': '12.747%',
        'Compounding Boost': '+0.747%',
        'Ending Balance': '$11,274.75',
        'Total Interest Earned': '+$1,274.75',
      },
    },
    faqs: [
      {
        question: 'What is the difference between APR and APY?',
        answer: 'APR (Annual Percentage Rate) reflects the simple annual interest rate without compounding. APY (Annual Percentage Yield) takes compound interest into account, reflecting the true annual return earned.',
      },
      {
        question: 'Why do DeFi protocols and crypto staking platforms quote APY?',
        answer: 'DeFi staking protocols often compound rewards continuously or daily. Quoting APY reflects the true return if rewards are systematically reinvested into the pool.',
      },
      {
        question: 'How does compounding frequency affect total yield?',
        answer: 'The more frequently interest compounds (daily vs annually), the higher the effective APY. However, the gains diminish: daily compounding yields nearly the same return as continuous compounding.',
      },
    ],
  },
  ...MORE_TOOLS,
  ...BATCH_3_TOOLS,
  ...BATCH_4_TOOLS,
  ...BATCH_5_TOOLS,
  ...BATCH_6_TOOLS,
];

export const CATEGORIES: { id: string; label: string; description: string; icon: string }[] = [
  {
    id: 'all',
    label: 'All Calculators',
    description: 'Browse our complete suite of 100 verified cryptocurrency and personal finance calculators.',
    icon: 'Grid',
  },
  {
    id: 'crypto',
    label: 'Cryptocurrency',
    description: 'Tools for crypto profit/loss, ROI, Dollar-Cost Averaging, staking yields, trading fees, and tax estimates.',
    icon: 'Coins',
  },
  {
    id: 'loans',
    label: 'Loans & Credit',
    description: 'Accurate amortization, auto loan EMI, personal loan financing, and 30-year home mortgages.',
    icon: 'Landmark',
  },
  {
    id: 'investment',
    label: 'Investment & SIP',
    description: 'Compound growth models, Systematic Investment Plans (SIP), and portfolio return metrics.',
    icon: 'TrendingUp',
  },
  {
    id: 'savings',
    label: 'Savings & Goals',
    description: 'Plan emergency funds, high-yield bank interest, and systematic wealth-building targets.',
    icon: 'PiggyBank',
  },
];

export function getToolBySlug(slug: string): ToolItem | undefined {
  return TOOLS.find((t) => t.slug === slug || t.route === `/${slug}` || t.id === slug);
}

export function getToolsByCategory(category: string): ToolItem[] {
  if (!category || category === 'all') return TOOLS;
  return TOOLS.filter((t) => t.category === category);
}

export function searchTools(query: string): ToolItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  return TOOLS.filter((t) => {
    return (
      t.name.toLowerCase().includes(q) ||
      t.shortDescription.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q) ||
      t.categoryLabel.toLowerCase().includes(q) ||
      t.keywords.some((k) => k.toLowerCase().includes(q))
    );
  });
}
