import React from 'react';
import { AlertTriangle } from 'lucide-react';
import { Breadcrumbs } from '../common/Breadcrumbs';

export { PrivacyPolicyPage } from './PrivacyPolicyPage';
export { TermsPage } from './TermsPage';

interface LegalPageProps {
  onNavigate: (route: string) => void;
}

// 3. Disclaimer
export const DisclaimerPage: React.FC<LegalPageProps> = ({ onNavigate }) => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      <Breadcrumbs items={[{ label: 'Disclaimer' }]} onNavigate={onNavigate} />

      <div className="mb-10 pb-6 border-b border-slate-200 dark:border-slate-800">
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight flex items-center gap-3">
          <AlertTriangle className="w-8 h-8 text-amber-500" />
          <span>Financial & Investment Disclaimer</span>
        </h1>
        <p className="mt-2 text-xs sm:text-sm text-slate-500 dark:text-slate-400">
          Mandatory Regulatory Disclosure
        </p>
      </div>

      <div className="space-y-6 text-slate-600 dark:text-slate-400 text-sm sm:text-base leading-relaxed">
        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100 mb-2">
            Not Financial, Tax, or Legal Advice
          </h2>
          <p>
            The information, formulas, and estimates generated by FinCalc Pro are provided strictly for educational and self-directed exploratory purposes. <strong>FinCalc Pro is not a registered investment advisor, broker-dealer, financial planner, or certified tax professional.</strong>
          </p>
          <p className="mt-3">
            None of the content or calculation outputs constitute a recommendation or solicitation to purchase or liquidate any security, digital asset, cryptocurrency, commodity, or mortgage product.
          </p>
        </div>

        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100 mb-2">
            Market Risks & Volatility
          </h2>
          <p>
            Cryptocurrency assets are subject to extreme market volatility, smart contract risks, regulatory uncertainty, and potential total loss of capital. Past performance or theoretical historical DCA yields do not predict or guarantee future market returns.
          </p>
          <p className="mt-3">
            Always consult a qualified certified financial planner (CFP) or certified public accountant (CPA) before making significant financial commitments or tax filings.
          </p>
        </div>
      </div>
    </div>
  );
};

// 4. Affiliate Disclosure
export const AffiliateDisclosurePage: React.FC<LegalPageProps> = ({ onNavigate }) => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      <Breadcrumbs items={[{ label: 'Affiliate Disclosure' }]} onNavigate={onNavigate} />

      <div className="mb-10 pb-6 border-b border-slate-200 dark:border-slate-800">
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight">
          Affiliate & Advertising Disclosure
        </h1>
        <p className="mt-2 text-xs sm:text-sm text-slate-500 dark:text-slate-400">
          FTC Compliance & Transparent Monetization Policy
        </p>
      </div>

      <div className="space-y-6 text-slate-600 dark:text-slate-400 text-sm sm:text-base leading-relaxed">
        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100 mb-2">
            1. FTC Compliance Notice
          </h2>
          <p>
            In compliance with Federal Trade Commission (FTC) guidelines, please assume that certain links, banner advertisements, or product references on this site may be affiliate links.
          </p>
          <p className="mt-3">
            If you click on an affiliate link and choose to sign up or purchase a service (such as a hardware wallet, banking service, or crypto exchange), FinCalc Pro may earn a small referral commission at absolutely no additional cost to you.
          </p>
        </div>

        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100 mb-2">
            2. Mathematical Independence
          </h2>
          <p>
            Our calculation formulas, interest calculations, fee comparisons, and mathematical algorithms are 100% independent and unaffected by any advertiser relationships. We never alter formulas or inflate returns for any commercial partner.
          </p>
        </div>
      </div>
    </div>
  );
};
